const env = process.env

export const CONFIG = {
  ENV: env.ENV,
  PORT: env.PORT,
  DB_URI: env.DB_URI,
  ORIGIN: env.ORIGIN,
  JWT_SECRET: env.JWT_SECRET,
  // JWT_REFRESH_TOKEN: env.JWT_REFRESH_TOKEN,
  REDIS_URL: env.REDIS_URL,
  EMAIL_ADDRESS: env.EMAIL_ADDRESS,
  PUBLIC_VAPID_KEYS: env.PUBLIC_VAPID_KEYS,
  PRIVATE_VAPID_KEYS: env.PRIVATE_VAPID_KEYS,

  // MAIL TOKEN
  CLIENT_ID: env.CLIENT_ID,
  PROJECT_ID: env.PROJECT_ID,
  //AUTH_URI: env.AUTH_URI,
  //TOKEN_URI: env.TOKEN_URI,
  //AUTH_PROVIDER_X509_CERT_URL: env.AUTH_PROVIDER_X509_CERT_URL,
  CLIENT_SECRET: env.CLIENT_ID,
  REDIRECT_URL: env.REDIRECT_URL,
  REFRESH_TOKEN: env.REFRESH_TOKEN
}
